apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helmfiles-app
  namespace: argocd
spec:
  project: default
  source:
#mention your own repo which include the helmfile.yaml and define the path
    repoURL: git@github.com:rorobig/congenial-palm-tree.git
    targetRevision: HEAD
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: my-helmfiles-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2